#
# Module manifest for module 'PSPredictor' (Modular Version)
#
# Generated by: Sarin Na Wangkanai
#
# Generated on: 2025-07-30
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSPredictor.psm1'

# Version number of this module.
ModuleVersion = '1.1.0'

# Supported PSEditions
CompatiblePSEditions = @('Core')

# ID used to uniquely identify this module
GUID = '12345678-1234-5678-9012-123456789012'

# Author of this module
Author = 'Sarin Na Wangkanai'

# Company or vendor of this module
CompanyName = 'wangkanai'

# Copyright statement for this module
Copyright = '(c) 2025 Sarin Na Wangkanai. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell Universal CLI Predictor - Intelligent auto-completion for 26+ popular CLI tools including Git, Docker, npm, Azure, AWS, .NET, Python, AI tools (Claude, Gemini), shells (PowerShell, Zsh, Bash), and more. Cross-platform support for PowerShell 7+ with modular architecture.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('PSReadLine')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Install-PSPredictor',
    'Uninstall-PSPredictor',
    'Get-PSPredictorCompletion',
    'Set-PSPredictorConfig',
    'Register-PSPredictorCompletion',
    'Unregister-PSPredictorCompletion',
    'Update-PSPredictorCompletions',
    'Enable-PSPredictorTool',
    'Disable-PSPredictorTool',
    'Get-PSPredictorTools'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @('pspredict', 'psp')

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('PowerShell', 'CLI', 'Completion', 'TabCompletion', 'Git', 'Docker', 'NPM', 'kubectl', 'Azure', 'AWS', 'Python', 'AI', 'Claude', 'Gemini', 'Homebrew', 'Cross-Platform', 'PowerShell7', 'Podman', 'tmux', 'DotNet', 'GitHub', 'Terraform', 'Bash', 'Zsh', 'Shell')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/wangkanai/PSPredictor/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/wangkanai/PSPredictor'

        # A URL to an icon representing this module.
        # IconUri = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

        # Release notes for this module
        ReleaseNotes = @'
## Version 1.1.0
- Major expansion: Now supports 26+ CLI tools (was 9)
- New completion providers: .NET, Claude AI, Gemini AI, GitHub CLI, Podman, tmux, Hyper, OpenAI Codex, Homebrew, npx, pip, pipx, pyenv, Python
- Shell completion support: PowerShell (pwsh), Zsh, Bash with comprehensive options and configurations
- Modular architecture for better maintainability and extensibility
- PowerShell 7+ cross-platform support (Windows, Linux, macOS)
- Enhanced Git, Docker, npm, Azure, AWS, kubectl, Terraform completions
- Improved configuration management with per-tool settings
- Silent module loading with optimized performance
- Comprehensive test suite with per-tool test organization (67+ tests)
- Updated documentation with complete tool coverage and shell support
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

# Release notes for this module moved to PrivateData for compatibility
# ReleaseNotes in PrivateData.PSData below

}