name: Markdown Lint

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    paths: [ '**.md' ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@v16
      with:
        globs: |
          **/*.md
          !node_modules/**/*.md
          !**/node_modules/**/*.md
        config: '.markdownlint.json'
        fix: false

    - name: Upload markdownlint results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: markdownlint-results
        path: markdownlint-results.json
